

#eureka:
#  instance:
#    preferIpAddress: true
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#
#gateway:
#  ip: 192.168.1.244
#
#token:
#  expiration_time: 3600000
#  secret: QbWNI8JMDD0oNYgF3qd7md3Y1LksrZf0wMA1EdWZmYpxiyA1r0hsdKrvEgvhlOMU




#    com.puihay.photoapp.api.users.PhotoAppApiUsers.data.AlbumsServiceClient: DEBUG
#    com.puihay.photoapp.api.users.PhotoAppApiUsers.service.UsersServiceImpl: DEBUG