server.port: ${PORT:0}

spring:
  application:
    name: users-ws
  config:
    import: optional:configserver:http://localhost:8012
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: puihayyip
    password: P@ssw0rd123

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

gateway:
  ip: 192.168.1.244

token:
  expiration_time: 3600000
  secret: QbWNI8JMDD0oNYgF3qd7md3Y1LksrZf0wMA1EdWZmYpxiyA1r0hsdKrvEgvhlOMU

authorization.token.header.name: Authorization
authorization.token.header.prefix: Bearer
login.url.path: /users-ws/users/login

logging:
  level:
    com.puihay.photoapp.api.users.PhotoAppApiUsers.data.AlbumsServiceClient: DEBUG
    com.puihay.photoapp.api.users.PhotoAppApiUsers.service.UsersServiceImpl: DEBUG