spring:
  application:
    name: PhotoAppApiConfigServer
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/puihayyip/NHPS
          search-paths:
            - ConfigurationFolder
          username: puihayyip
#          password: ${{ secrets.repo_access_token }}
          password: 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
          clone-on-start: true
          default-label: main

  rabbitmq:
    host: localhost
    port: 5672
    username: puihayyip
    password: P@ssw0rd123

server:
  port: 8012

management:
  endpoints:
    web:
      exposure:
        include: busrefresh

