server.port: ${PORT:0}

spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/photo_app?serverTimezone=UTC
    username: puihayyip
    password: '{cipher}AQBzW+lHeVKvqVyMIfIHzMLlxEeaaV+etO6d0nQsjqcf2+x2iJ/heltA3YtKZ0p81fs2LSQGkiWe07OUQZ0Wp5BmBYHlD8n9GdRwVG3hrz/AEeDSI6ksKw6+GfUViwr7iOgv9uVB6i7z9IL24PDQyyVnEtIh1fWIL/poI8VCVZQxW9rTs/R7GOrKp6HsEk53rie6Zc91v7MMJao7aShk/BkiQH0FeJLQMXsAAYX/gtMLDsDJrxoi1BLj/WeupcJOzmwePh/D5lMpRE08gnYhuBW0xcDipdlzQBTRK9lELjgyfY4nL1vFiuGF8F1HxFyCacCd7JLb01GHgpFeA5G7z7UX8iUPDZeo1PXAYahdpnrObkyOM93NWcSfuWoNyRrMD+A='


logging.file.name: albums-ws.log

authorization.token.header:
  name: Authorization
  prefix: Bearer

logging.level.com.team42.NHPS.api.Albums:
  service.AlbumsServiceImpl: DEBUG