login.url.path: /users-ws/users/login

server.port: ${PORT:0}

spring:
  application.name: users-ws
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/photo_app?serverTimezone=UTC
    username: puihayyip
    password: '{cipher}AQBzW+lHeVKvqVyMIfIHzMLlxEeaaV+etO6d0nQsjqcf2+x2iJ/heltA3YtKZ0p81fs2LSQGkiWe07OUQZ0Wp5BmBYHlD8n9GdRwVG3hrz/AEeDSI6ksKw6+GfUViwr7iOgv9uVB6i7z9IL24PDQyyVnEtIh1fWIL/poI8VCVZQxW9rTs/R7GOrKp6HsEk53rie6Zc91v7MMJao7aShk/BkiQH0FeJLQMXsAAYX/gtMLDsDJrxoi1BLj/WeupcJOzmwePh/D5lMpRE08gnYhuBW0xcDipdlzQBTRK9lELjgyfY4nL1vFiuGF8F1HxFyCacCd7JLb01GHgpFeA5G7z7UX8iUPDZeo1PXAYahdpnrObkyOM93NWcSfuWoNyRrMD+A='
  rabbitmq:
    host: localhost
    port: 5672
    username: puihayyip
    password: '{cipher}AQATs6talcke+7pDPAxw49KPLvveLSLCdSTWNcEcx0CpTxg2f4dqjYJUl0c8+NqRnYUsEz57BkZMKL/mmESLsZg5d7bKrC3HROjxbCwdCREFiWWrTwyo6T5O3napvpGWonFhOdlg7Mmx2iRV24cOLJzrdJQ+5elUZW4JBR4zSPa4BDty0qYim06GYop83PDRa55m+bWqt5FHWTQ3K/F1/xpBpOOl0OZncVErZeLOBU7sodMd3/zPsCn2vRu++zlExFz0JV9k9YpCc87Th7bu9yMji0Ei6JOraqAFuXqMJmgW5ClweE3cSK/RZE6teWqgb14g7V3gHSdjkUquAiweW0rmqMOaNchh7VdA7wCjg3E5ZbajmrlTwt0zC1sPuiqORfI='

albums:
  url: http://albums-ws/users/%s/albums
  exceptions:
    albums-not-found: User's albums are not found

logging.file.name: users-ws.log

authorization.token.header:
  name: Authorization
  prefix: Bearer

logging.level.com.team42.NHPS.api.Users:
  data.AlbumsServiceClient: DEBUG
  service.UsersServiceImpl: DEBUG